language: node_js
node_js:
  - "node"
install:
  - npm i -g npm@5.8.0
  - npm ci
before_script:
  - npx danger ci
script:
  - npx lerna run prepare
branches:
  only:
    - master
    - next
cache:
  directories:
    - "$HOME/.npm"
